name: Pull Request checks

on:
  pull_request:
    branches:
      - '!main'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install yarn dependencies
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: install # will run `yarn install` command
    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: export # will run `yarn export` command
    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: lint # will run `yarn lint` command
